[API]
# whether to extract predicates and constants
ENABLE_EXTRACTION = False
# whether to fix syntax
ENABLE_FIX = True
# whether to fix semantics
ENABLE_SELECTION = False
# whether to query knowledge base
ENABLE_KNOWLEDGE = False

; LSAT
DATATYPE = lsat
KB_ID = 671f5a33ee2660c0da1fb987

; LogiQA
; DATATYPE = logiqa
; KB_ID = 6756ee4b155ca7fd24bc5521

# 0-2, default is usually 1
TEMPERATURE = 0.2
CHECKER_TEMPATURE = 0.2
MAX_RETRY = 5

EMBEDDING_KEY = OPENAI_API_KEY
EMBEDDING_URL = https://api.openai.com/v1
EMBEDDING_MODEL = text-embedding-ada-002

FASTPGT_URL = https://fastgpt.chatyx.net
FASTPGT_API_KEY = fastgpt-

K_NUM = 0
STATIC_NUM = 0

API_SECRET_KEY = OPENAI_API_KEY
BASE_URL = https://api.openai.com/v1
MODEL = gpt-4o-mini

# API exclusively for checker
CHECKER_KEY = OPENAI_API_KEY
CHECKER_URL = https://api.openai.com/v1
CHECKER_MODEL = gpt-4o-mini
